package mybatis.entity;

import java.util.Date;

public class AdminUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_users.UserID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_users.UserAccount
     *
     * @mbggenerated
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_users.UserPassword
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_users.CreateDate
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_users.EditDate
     *
     * @mbggenerated
     */
    private Date editDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_users.UserID
     *
     * @return the value of t_admin_users.UserID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_users.UserID
     *
     * @param userId the value for t_admin_users.UserID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_users.UserAccount
     *
     * @return the value of t_admin_users.UserAccount
     *
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_users.UserAccount
     *
     * @param userAccount the value for t_admin_users.UserAccount
     *
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_users.UserPassword
     *
     * @return the value of t_admin_users.UserPassword
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_users.UserPassword
     *
     * @param userPassword the value for t_admin_users.UserPassword
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_users.CreateDate
     *
     * @return the value of t_admin_users.CreateDate
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_users.CreateDate
     *
     * @param createDate the value for t_admin_users.CreateDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_users.EditDate
     *
     * @return the value of t_admin_users.EditDate
     *
     * @mbggenerated
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_users.EditDate
     *
     * @param editDate the value for t_admin_users.EditDate
     *
     * @mbggenerated
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }
}