package mybatis.entity;

public class AdminUsersRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adminusers_role.UserRoleID
     *
     * @mbggenerated
     */
    private Integer userRoleID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adminusers_role.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_adminusers_role.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adminusers_role.UserRoleID
     *
     * @return the value of t_adminusers_role.UserRoleID
     *
     * @mbggenerated
     */
    public Integer getUserRoleID() {
        return userRoleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adminusers_role.UserRoleID
     *
     * @param userRoleID the value for t_adminusers_role.UserRoleID
     *
     * @mbggenerated
     */
    public void setUserRoleID(Integer userRoleID) {
        this.userRoleID = userRoleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adminusers_role.userId
     *
     * @return the value of t_adminusers_role.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adminusers_role.userId
     *
     * @param userId the value for t_adminusers_role.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_adminusers_role.roleId
     *
     * @return the value of t_adminusers_role.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_adminusers_role.roleId
     *
     * @param roleId the value for t_adminusers_role.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}