package mybatis.entity;

public class AdminPrivilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_privilege.privilegeId
     *
     * @mbggenerated
     */
    private Integer privilegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_privilege.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_privilege.moduleId
     *
     * @mbggenerated
     */
    private Integer moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_privilege.privilegeId
     *
     * @return the value of t_admin_privilege.privilegeId
     *
     * @mbggenerated
     */
    public Integer getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_privilege.privilegeId
     *
     * @param privilegeId the value for t_admin_privilege.privilegeId
     *
     * @mbggenerated
     */
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_privilege.roleId
     *
     * @return the value of t_admin_privilege.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_privilege.roleId
     *
     * @param roleId the value for t_admin_privilege.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_privilege.moduleId
     *
     * @return the value of t_admin_privilege.moduleId
     *
     * @mbggenerated
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_privilege.moduleId
     *
     * @param moduleId the value for t_admin_privilege.moduleId
     *
     * @mbggenerated
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }
}