package mybatis.dao;

import java.util.List;
import mybatis.entity.AdminRole;
import mybatis.entity.AdminRoleExample;
import org.apache.ibatis.annotations.Param;

public interface AdminRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role
     *
     * @mbggenerated
     */
    int countByExample(AdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role
     *
     * @mbggenerated
     */
    int deleteByExample(AdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role
     *
     * @mbggenerated
     */
    int insert(AdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role
     *
     * @mbggenerated
     */
    int insertSelective(AdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role
     *
     * @mbggenerated
     */
    List<AdminRole> selectByExample(AdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role
     *
     * @mbggenerated
     */
    AdminRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AdminRole record, @Param("example") AdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AdminRole record, @Param("example") AdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminRole record);
}