package mybatis.dao;

import java.util.List;
import mybatis.entity.AdminPrivilege;
import mybatis.entity.AdminPrivilegeExample;
import org.apache.ibatis.annotations.Param;

public interface AdminPrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_privilege
     *
     * @mbggenerated
     */
    int countByExample(AdminPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_privilege
     *
     * @mbggenerated
     */
    int deleteByExample(AdminPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_privilege
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer privilegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_privilege
     *
     * @mbggenerated
     */
    int insert(AdminPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_privilege
     *
     * @mbggenerated
     */
    int insertSelective(AdminPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_privilege
     *
     * @mbggenerated
     */
    List<AdminPrivilege> selectByExample(AdminPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_privilege
     *
     * @mbggenerated
     */
    AdminPrivilege selectByPrimaryKey(Integer privilegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_privilege
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AdminPrivilege record, @Param("example") AdminPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_privilege
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AdminPrivilege record, @Param("example") AdminPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_privilege
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_privilege
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminPrivilege record);
}